/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 paper.glb --transform 
Files: paper.glb [64.64KB] > paper-transformed.glb [9.06KB] (86%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Paper(props) {
	const { nodes, materials } = useGLTF("/paper-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Object_4.geometry}
				material={materials.paper}
				position={[0.007, 0.017, 0.063]}
			/>
		</group>
	);
}

useGLTF.preload("/paper-transformed.glb");
